name: entri_education_video_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  carousel_slider: 5.0.0
  cloud_firestore: ^5.6.5
  cloud_firestore_platform_interface: ^6.6.5
  cloud_firestore_web: ^4.4.5
  collection:
  connectivity_plus:
  csslib:
  currency_symbols: ^0.0.1+2
  device_info_plus:
  devicelocale:
  dots_indicator:
  easy_debounce: ^2.0.3
  equatable: ^2.0.7
  expandable: 5.0.1
  file_picker: ^9.0.2
  firebase_auth: ^5.5.1
  firebase_auth_platform_interface: ^7.6.1
  firebase_auth_web: ^5.14.1
  firebase_core: ^3.12.1
  firebase_core_platform_interface: ^5.4.0
  firebase_core_web: ^2.21.1
  firebase_messaging: any
  firebase_performance: ^0.10.1+4
  firebase_performance_platform_interface: ^0.1.5+4
  firebase_performance_web: ^0.1.7+10
  firebase_storage: ^12.4.4
  firebase_storage_platform_interface: ^5.2.4
  firebase_storage_web: ^3.10.11
  flutter_animate: ^4.5.2
  flutter_cache_manager: 3.4.1
  flutter_html:
  flutter_inappwebview: ^6.1.5
  flutter_keyboard_visibility: 6.0.0
  flutter_keyboard_visibility_linux: 1.0.0
  flutter_keyboard_visibility_macos: 1.0.0
  flutter_keyboard_visibility_platform_interface: 2.0.0
  flutter_keyboard_visibility_web: 2.0.0
  flutter_keyboard_visibility_windows: 1.0.0
  flutter_local_notifications: ^18.0.1
  flutter_paypal: any
  flutter_plugin_android_lifecycle: ^2.0.27
  flutter_rating_bar: 4.0.1
  flutter_stripe: ^11.4.0
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.8.0
  from_css_color: 2.0.0
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  google_sign_in_android: ^6.2.0
  google_sign_in_ios: ^5.8.1
  google_sign_in_platform_interface: ^2.5.0
  google_sign_in_web: ^0.12.4+4
  html:
  http: ^1.3.0
  image_picker: 1.1.2
  image_picker_android: ^0.8.12+22
  image_picker_for_web: ^3.0.6
  image_picker_ios: ^0.8.12+2
  image_picker_linux: 0.2.1+1
  image_picker_macos: ^0.2.1+2
  image_picker_platform_interface: ^2.10.1
  image_picker_windows: 0.2.1+1
  in_app_review: ^2.0.10
  intl:
  intl_phone_field:
  json_path: ^0.7.5
  lottie: ^3.3.1
  markdown: ^7.3.0
  mime_type: ^1.0.1
  open_file:
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  path_provider_android: ^2.2.16
  path_provider_foundation: ^2.4.1
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  pdf:
  percent_indicator: ^4.2.4
  permission_handler: ^11.4.0
  pin_code_fields: 8.0.1
  plugin_platform_interface: 2.1.8
  pointer_interceptor: 0.10.1+2
  pointer_interceptor_ios: 0.10.1
  pointer_interceptor_platform_interface: 0.10.0+1
  pointer_interceptor_web: 0.10.2+1
  provider: 6.1.2
  range_slider_flutter: ^0.0.2
  razorpay_flutter: ^1.4.0
  rxdart: ^0.28.0
  share_plus: ^10.1.4
  share_plus_platform_interface: ^5.0.2
  shared_preferences: ^2.5.2
  shared_preferences_android: ^2.4.8
  shared_preferences_foundation: ^2.5.4
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: ^2.4.3
  shared_preferences_windows: 2.4.1
  sign_in_with_apple: ^6.1.4
  sign_in_with_apple_platform_interface: 1.1.0
  sign_in_with_apple_web: ^2.1.1
  socket_io_client: ^3.0.2
#  sqflite: ^2.4.2
#  sqflite_common: ^2.5.5
  stream_transform: ^2.1.1
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.15
  url_launcher_ios: ^6.3.2
  url_launcher_linux: ^3.2.1
  url_launcher_macos: ^3.2.2
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: ^2.4.0
  url_launcher_windows: ^3.1.4
  uuid: ^4.5.1
  video_player: ^2.9.3
  video_player_android: ^2.8.1
  video_player_avfoundation: ^2.7.0
  video_player_platform_interface: ^6.3.0
  video_player_web: ^2.3.4
  wakelock_plus:
  webview_flutter:
  webview_flutter_android:
  webview_flutter_platform_interface: 2.10.0
  webview_flutter_wkwebview: ^3.18.4
  webviewx_plus: 0.5.0
  youtube_player_iframe: 
    git:
      url: https://github.com/FlutterFlow/youtube_player_flutter.git
      path: packages/youtube_player_iframe

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dependency_overrides:
  http: ^1.3.0
  pointer_interceptor: 0.10.1+2
  pointer_interceptor_ios: 0.10.1
  pointer_interceptor_platform_interface: 0.10.0+1
  pointer_interceptor_web: 0.10.2+1
  uuid: ^4.5.1
#  win32: ^5.11.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  image: ^4.5.3
  lints: ^5.1.1
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/

  fonts:
    - family: 'SF Pro Display'
      fonts:
        - asset: assets/fonts/regular.ttf
        - asset: assets/fonts/medium.ttf
          weight: 500
        - asset: assets/fonts/semibold.ttf
          weight: 600
        - asset: assets/fonts/bold.ttf
          weight: 700
    - family: 'Satoshi'
      fonts:
        - asset: assets/fonts/Satoshi-Regular.ttf
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 700

    - family: Entrieducationapp
      fonts:
        - asset: assets/fonts/Entrieducationapp.ttf
    - family: Search
      fonts:
        - asset: assets/fonts/Search.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

